---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dcis-commons-prod
  namespace: argocd
spec:
  project: torganized-play
  sources:
  - repoURL: quay.io/paladinsinn/helm
    chart: dcis-commons
    targetRevision: 1.0.0-SNAPSHOT
    helm:
      valueFiles:
      - $values/torganized-play/dcis-commons.yaml
  - repoURL: https://github.com/KaiserpfalzEDV/cluster-gitops.git
    targetRevision: main
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: torganized-play
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
