#
# This is an insecure configuration!
# It will open a docker container listening on port 80.
# You will need to set "net.ipv4.ip_unprivileged_port_start=80" (at least port 80)
# to make this work.
#
services:
  proxy:
    container_name: proxy
    image: docker.io/nginx:latest
    restart: on-failure
    ports:
    - 8080:8080
    volumes:
    - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
    - ./../src/main/html/commons/1.0.0/assets/img/favicon.ico:/etc/nginx/html/favicon.ico
    - ./../src/main/html/index.html:/etc/nginx/html/index.html
    depends_on:
      dcis-commons:
        condition: service_healthy
      dcis-users:
        condition: service_healthy
      dcis-gaming:
        condition: service_healthy
      dcis-threats:
        condition: service_healthy

# ==============================================================================
# DCIS - Commons
# ------------------------------------------------------------------------------
  dcis-commons:
    profiles:
    - services
    container_name: dcis-commons
    restart: always
    image: quay.io/paladinsinn/dcis/dcis-commons:1.0.0-SNAPSHOT
    ports:
    - 8090:8080

# ==============================================================================
# DCIS - Users
# ------------------------------------------------------------------------------
  dcis-users:
    profiles:
    - dcis-users
    - services
    container_name: dcis-users
    image: quay.io/paladinsinn/dcis/dcis-users:1.0.0-SNAPSHOT
    depends_on:
      dcis-users-db:
        condition: service_healthy
    ports:
    - 8081:8080
    - 8091:8081
    environment:
      SPRING_PROFILES_ACTIVE: LOCAL
      PGO_pgbouncer-jdbc-uri: jdbc:postgresql://dcis-users-db:5432/postgres?user=postgres&password=postgres
      PGO_user: postgres
      PGO_password: postgres
      SSO_ISSUER: https://sso.kaiserpfalz-edv.de/realms/delphi-council
      SSO_CLIENT_ID: klenkes74
      SSO_ROLE_ATTRIBUTE: groups
      SSO_USERNAME_ATTRIBUTE: preferred_username
      SSO_SCOPES: openid,profile,email,roles
    env_file: 
    - dev-dcis.env
      # This file currently only contains a single line:
      # SSO_CLIENT_SECRET: <oidc client secret for the provider>
      # It is excluded via .gitignore from being checked into github.
    volumes:
    - ../../torganized-play-users/src/main/resources/application.yaml:/deployments/application.yaml:ro
    tmpfs:
    - /tmp
    - /var/lib/run

  dcis-users-db:
    profiles:
    - databases
    container_name: dcis-users-db
    image: docker.io/postgres:16.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
    - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    volumes: 
      - dev-users-db:/var/lib/postgresql/data:rw
    tmpfs:
    - /tmp
    - /var/lib/run


# ==============================================================================
# DCIS - Operatives
# ------------------------------------------------------------------------------
  dcis-operatives:
    profiles:
    - dcis-operatives
    - services
    container_name: dcis-operatives
    image: quay.io/paladinsinn/dcis/dcis-operatives:1.0.0-SNAPSHOT
    depends_on:
      dcis-operatives-db:
        condition: service_healthy
    ports:
    - 8082:8080
    - 8092:8081
    environment:
      SPRING_PROFILES_ACTIVE: LOCAL
      PGO_pgbouncer-jdbc-uri: jdbc:postgresql://dcis-operatives-db:5432/postgres?user=postgres&password=postgres
      PGO_user: postgres
      PGO_password: postgres
      SSO_ISSUER: https://sso.kaiserpfalz-edv.de/realms/delphi-council
      SSO_CLIENT_ID: klenkes74
      SSO_ROLE_ATTRIBUTE: groups
      SSO_USERNAME_ATTRIBUTE: preferred_username
      SSO_SCOPES: openid,profile,email,roles
    env_file: 
    - dev-dcis.env
      # This file currently only contains a single line:
      # SSO_CLIENT_SECRET: <oidc client secret for the provider>
      # It is excluded via .gitignore from being checked into github.
    volumes:
    - ../../torganized-play-operatives/src/main/resources/application.yaml:/deployments/application.yaml:ro
    tmpfs:
    - /tmp
    - /var/lib/run

  dcis-operatives-db:
    profiles:
    - databases
    container_name: dcis-operatives-db
    image: docker.io/postgres:16.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
    - 5434:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    volumes: 
      - dev-operatives-db:/var/lib/postgresql/data:rw
    tmpfs:
    - /tmp
    - /var/lib/run


# ==============================================================================
# DCIS - Threats Database
# ------------------------------------------------------------------------------
  dcis-threats:
    profiles:
    - dcis-threats
    - services
    container_name: dcis-threats
    image: quay.io/paladinsinn/dcis/dcis-threats:1.0.0-SNAPSHOT
    depends_on:
      dcis-threats-db:
        condition: service_healthy
    ports:
    - 8082:8080
    - 8092:8081
    environment:
      SPRING_PROFILES_ACTIVE: LOCAL
      PGO_pgbouncer-jdbc-uri: jdbc:postgresql://dcis-threats-db:5432/postgres?user=postgres&password=postgres
      PGO_user: postgres
      PGO_password: postgres
      SSO_ISSUER: https://sso.kaiserpfalz-edv.de/realms/delphi-council
      SSO_CLIENT_ID: klenkes74
      SSO_ROLE_ATTRIBUTE: groups
      SSO_USERNAME_ATTRIBUTE: preferred_username
      SSO_SCOPES: openid,profile,email,roles
    env_file: 
    - dev-dcis.env
      # This file currently only contains a single line:
      # SSO_CLIENT_SECRET: <oidc client secret for the provider>
      # It is excluded via .gitignore from being checked into github.
    volumes:
    - ../../torganized-play-operatives/src/main/resources/application.yaml:/deployments/application.yaml:ro
    tmpfs:
    - /tmp
    - /var/lib/run

  dcis-threats-db:
    profiles:
    - databases
    container_name: dcis-threats-db
    image: docker.io/postgres:16.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
    - 5434:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    volumes: 
      - dev-threats-db:/var/lib/postgresql/data:rw
    tmpfs:
    - /tmp
    - /var/lib/run


# ==============================================================================
# DCIS - Threats Database
# ------------------------------------------------------------------------------
  dcis-gaming:
    profiles:
    - dcis-gaming
    - services
    container_name: dcis-gaming
    image: quay.io/paladinsinn/dcis/dcis-gaming:1.0.0-SNAPSHOT
    depends_on:
      dcis-gaming-db:
        condition: service_healthy
    ports:
    - 8082:8080
    - 8092:8081
    environment:
      SPRING_PROFILES_ACTIVE: LOCAL
      PGO_pgbouncer-jdbc-uri: jdbc:postgresql://dcis-gaming-db:5432/postgres?user=postgres&password=postgres
      PGO_user: postgres
      PGO_password: postgres
      SSO_ISSUER: https://sso.kaiserpfalz-edv.de/realms/delphi-council
      SSO_CLIENT_ID: klenkes74
      SSO_ROLE_ATTRIBUTE: groups
      SSO_USERNAME_ATTRIBUTE: preferred_username
      SSO_SCOPES: openid,profile,email,roles
    env_file: 
    - dev-dcis.env
      # This file currently only contains a single line:
      # SSO_CLIENT_SECRET: <oidc client secret for the provider>
      # It is excluded via .gitignore from being checked into github.
    volumes:
    - ../../torganized-play-operatives/src/main/resources/application.yaml:/deployments/application.yaml:ro
    tmpfs:
    - /tmp
    - /var/lib/run

  dcis-gaming-db:
    profiles:
    - databases
    container_name: dcis-gaming-db
    image: docker.io/postgres:16.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
    - 5434:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    volumes: 
      - dev-gaming-db:/var/lib/postgresql/data:rw
    tmpfs:
    - /tmp
    - /var/lib/run

volumes:
  dev-users-db:
    driver: local
  dev-gaming-db:
    driver: local
  dev-threats-db:
    driver: local
  dev-stormnights-db:
    driver: local